#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CustomVideoView.Resource", IsApplication=true)]

namespace CustomVideoView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f040000
			public const int seek_img = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int thumb = 2130968577;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000c
			public const int Black = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int Blue = 2131034127;
			
			// aapt resource value: 0x7f050005
			public const int Gray = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Gray_40 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Gray_60 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Gray_80 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Gray_90 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Gray_97 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int Gray_98 = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int Orange = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int Red = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int Red_10 = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int Red_49 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Red_Light = 2131034114;
			
			// aapt resource value: 0x7f05000d
			public const int Transparent = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int Transparent_50 = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int White = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int Yellow = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int Yellow_250 = 2131034130;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070025
			public const int Padding_12 = 2131165221;
			
			// aapt resource value: 0x7f07002a
			public const int Padding_120 = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int Padding_174 = 2131165227;
			
			// aapt resource value: 0x7f070026
			public const int Padding_30 = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int Padding_42 = 2131165223;
			
			// aapt resource value: 0x7f070029
			public const int Padding_66 = 2131165225;
			
			// aapt resource value: 0x7f070028
			public const int Padding_78 = 2131165224;
			
			// aapt resource value: 0x7f070024
			public const int ProductD_Pic_H = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int ProductD_Pic_W = 2131165219;
			
			// aapt resource value: 0x7f070007
			public const int Size_102 = 2131165191;
			
			// aapt resource value: 0x7f070021
			public const int Size_1212 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int Size_1254 = 2131165218;
			
			// aapt resource value: 0x7f070008
			public const int Size_126 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int Size_132 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int Size_144 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Size_150 = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int Size_18 = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int Size_180 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int Size_204 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int Size_216 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int Size_222 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int Size_240 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int Size_246 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int Size_252 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int Size_270 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int Size_282 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int Size_318 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int Size_324 = 2131165206;
			
			// aapt resource value: 0x7f070001
			public const int Size_36 = 2131165185;
			
			// aapt resource value: 0x7f070017
			public const int Size_450 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int Size_468 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int Size_480 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int Size_504 = 2131165210;
			
			// aapt resource value: 0x7f070002
			public const int Size_54 = 2131165186;
			
			// aapt resource value: 0x7f07001b
			public const int Size_552 = 2131165211;
			
			// aapt resource value: 0x7f070003
			public const int Size_66 = 2131165187;
			
			// aapt resource value: 0x7f07001c
			public const int Size_690 = 2131165212;
			
			// aapt resource value: 0x7f070004
			public const int Size_72 = 2131165188;
			
			// aapt resource value: 0x7f07001d
			public const int Size_756 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int Size_810 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int Size_864 = 2131165215;
			
			// aapt resource value: 0x7f070005
			public const int Size_90 = 2131165189;
			
			// aapt resource value: 0x7f070020
			public const int Size_948 = 2131165216;
			
			// aapt resource value: 0x7f070006
			public const int Size_96 = 2131165190;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int FullScreen = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Pause = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Play = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int MyButton = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int VideoViewLayout = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int VideoView_FrameLayout_video = 2131230725;
			
			// aapt resource value: 0x7f08000f
			public const int VideoView_ImageView_FullScreen = 2131230735;
			
			// aapt resource value: 0x7f080009
			public const int VideoView_ImageView_Pause = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int VideoView_ImageView_Play = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int VideoView_ImageView_Thumbnail = 2131230727;
			
			// aapt resource value: 0x7f08000e
			public const int VideoView_Layout_FullScreen = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int VideoView_Layout_VideoProgress = 2131230730;
			
			// aapt resource value: 0x7f080010
			public const int VideoView_ProgressBar_PB = 2131230736;
			
			// aapt resource value: 0x7f08000c
			public const int VideoView_SeekBar_SB = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int VideoView_TextView_VideoCurrentTime = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int VideoView_TextView_VideoTotalTime = 2131230733;
			
			// aapt resource value: 0x7f080006
			public const int VideoView_VideoView_video = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int iv = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int tv = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int video = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Test = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int VideoViewLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
